### ISSUE TITLE
admin.register decorator

### ISSUE THREAD

**Issue by namper** [nukikordzaia/carwash#1]
https://github.com/nukikordzaia/carwash/blob/f167710a98ce697664b663d9c46919a5fca0d31a/carwashs/admin.py#L12

აქ ჯობია `@admin.register(Model)` დეკორატორი გამოიყენო

**Comment by nukikordzaia** [comment]
მიშო აქ ვერ ვხვდები როგორ გავასწორო

**Comment by namper** [comment]
https://github.com/tsotnesharvadze/Graey-Education/blob/ac54de1758032df13d3c6e1334c754cafc3f66a1/back-end/BookStore-Django/book_store/store/admin.py#L11

**Comment by nukikordzaia** [comment]
mgonii scorad gavakete ?
